opt_out_usage

default_platform(:ios)

platform :ios do
  desc "Run unit tests"
  lane :test do
    scan(scheme: "LastDramTests")
  end

  desc "build"
  lane :build do
    sh("../.github/scripts/import-certificate.sh")
    sh("../.github/scripts/import-profile.sh")
    sh("../.github/scripts/set-env-vars.sh")
    build_app
  end
end
