opt_out_usage

default_platform(:ios)

platform :ios do
  desc "Run unit tests"
  lane :test do
    scan(scheme: "LastDramTests")
  end

  desc "build"
  lane :build do
    sh("cd .. && fastlane/import-certificate.sh")
    sh("cd .. && fastlane/import-profile.sh")
    sh("cd .. && fastlane/set-env-vars.sh")
    build_app(scheme: "LastDram")
  end
end
