name: Check PR Title

on:
  pull_request:
    branches: [ main ]
    types: [ edited, opened, reopened, synchronize ]

jobs:
  test:
    name: PR Title Check
    runs-on: ubuntu-latest
    steps:
      - name: Check Title
        uses: ExpediaGroup/github-helpers@v1
        with:
          helper: check-pr-title
          github_token: ${{ secrets.GITHUB_TOKEN }}