name: Deploy

on:
  pull_request:
    branches:
      - main
    paths:
      - 'LastDram/**'
      - '.github/workflows/deploy.yml'
  release:
    types:
      - edited
      - published

env:
  PRODUCT_NAME: LastDram
  API_URL: ${{ secrets.API_URL }}
  API_KEY: ${{ secrets.API_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SIGNING_CERTIFICATE_P12_DATA: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA }}
  SIGNING_CERTIFICATE_PASSWORD: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}
  PROVISIONING_PROFILE_DATA: ${{ secrets.PROVISIONING_PROFILE_DATA }}

jobs:
  deploy:
    name: Deploy to App Store Connect
    runs-on: macos-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Build app
        run: npm run build

      - if: github.event_name == 'release'
        name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.PRODUCT_NAME }}.ipa
            ${{ env.PRODUCT_NAME }}.app.dSYM.zip

      - if: github.event_name == 'release'
        name: Upload app to App Store Connect
        run: |
          xcrun altool --upload-app \
            -t ios \
            -f "${{ env.PRODUCT_NAME }}.ipa" \
            -u "${{ secrets.APP_STORE_CONNECT_USERNAME }}" \
            -p "${{ secrets.APP_STORE_CONNECT_PASSWORD }}"