name: deploy

on:
  push:
    branches: [ main ]
    tags: [ v* ]

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set environment variables from project settings
        run: .github/scripts/set-env-from-xcodeproj.sh

      - name: Inject environment variables
        run: |
          sed -i '' "s/REPLACE_ME_WITH_API_URL/${{ secrets.API_URL }}/g" LastDram/EnvironmentVariables.swift
          sed -i '' "s/REPLACE_ME_WITH_API_KEY/${{ secrets.API_KEY }}/g" LastDram/EnvironmentVariables.swift

      - name: Import signing certificate
        run: .github/scripts/import-certificate.sh
        env:
          SIGNING_CERTIFICATE_P12_DATA: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA }}
          SIGNING_CERTIFICATE_PASSWORD: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}

      - name: Import provisioning profile
        run: .github/scripts/import-profile.sh
        env:
          PROVISIONING_PROFILE_DATA: ${{ secrets.PROVISIONING_PROFILE_DATA }}

      - name: Build app
        run: fastlane run build_app

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build.log
          path: ~/Library/Logs/gym/*.log

      - name: Upload release assets
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.PRODUCT_NAME }}.ipa
            ${{ env.PRODUCT_NAME }}.app.dSYM.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload app to App Store Connect
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          APP_STORE_CONNECT_USERNAME: ${{ secrets.APP_STORE_CONNECT_USERNAME }}
          APP_STORE_CONNECT_PASSWORD: ${{ secrets.APP_STORE_CONNECT_PASSWORD }}
        run: |
          xcrun altool --upload-app \
            -t ios \
            -f "$PRODUCT_NAME.ipa" \
            -u "$APP_STORE_CONNECT_USERNAME" \
            -p "$APP_STORE_CONNECT_PASSWORD"