name: Deploy

on:
  pull_request:
    branches:
      - main
    paths:
      - 'LastDram/**'
      - '.github/workflows/deploy.yml'
  release:
    types:
      - edited
      - published

env:
  PRODUCT_NAME: LastDram

jobs:
  deploy:
    name: Deploy to App Store Connect
    runs-on: macos-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Import signing certificate
        run: .github/scripts/import-certificate.sh
        env:
          SIGNING_CERTIFICATE_P12_DATA: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA }}
          SIGNING_CERTIFICATE_PASSWORD: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}

      - name: Import provisioning profile
        run: .github/scripts/import-profile.sh
        env:
          PROVISIONING_PROFILE_DATA: ${{ secrets.PROVISIONING_PROFILE_DATA }}

      - name: Set project versions
        run: |
          VERSION_TAG=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          NEW_VERSION=${VERSION_TAG:1}
          echo NEW_VERSION=$NEW_VERSION
          xcrun agvtool new-version $NEW_VERSION
          sed -i '' "s#MARKETING_VERSION \= [^\;]*\;#MARKETING_VERSION = $NEW_VERSION;#g" LastDram.xcodeproj/project.pbxproj

      - name: Set environment variables
        run: |
          sed -i '' "s#REPLACE_ME_WITH_API_URL#${{ secrets.API_URL }}#g" LastDram/EnvironmentVariables.swift
          sed -i '' "s#REPLACE_ME_WITH_API_KEY#${{ secrets.API_KEY }}#g" LastDram/EnvironmentVariables.swift

      - name: Build app
        run: fastlane run build_app

      - if: github.event_name == 'release'
        name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.PRODUCT_NAME }}.ipa
            ${{ env.PRODUCT_NAME }}.app.dSYM.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: github.event_name == 'release'
        name: Upload app to App Store Connect
        run: |
          xcrun altool --upload-app \
            -t ios \
            -f "${{ env.PRODUCT_NAME }}.ipa" \
            -u "${{ secrets.APP_STORE_CONNECT_USERNAME }}" \
            -p "${{ secrets.APP_STORE_CONNECT_PASSWORD }}"