name: Exemptions

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  exemptions:
    name: Set Exemptions
    runs-on: ubuntu-latest
    steps:
      - uses: ExpediaGroup/github-helpers@v1
        with:
          helper: set-commit-status
          sha: ${{ github.event.pull_request.head.sha }}
          context: |
            Codegen Check
            SwiftLint
            Plan
            Unit Tests
          state: success
          description: Set to success in case workflow is skipped.
          github_token: ${{ secrets.GITHUB_TOKEN }}
