name: Lint

on:
  pull_request:
    paths:
      - '..swiftlint.yml'
      - '**/*.swift'
      - '.github/workflows/.swiftlint.yml'

jobs:
  SwiftLint:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v1

      - name: Lint code using SwiftLint
        run: swiftlint lint --reporter github-actions-logging