name: Lint

on:
  pull_request:
    paths:
      - '..swiftlint.yml'
      - '**/*.swift'
      - '.github/workflows/swiftlint.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: SwiftLint
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Lint
        run: npm run lint