name: Lint

on:
  pull_request:
    paths:
      - '..swiftlint.yml'
      - '**/*.swift'
      - '.github/workflows/swiftlint.yml'

jobs:
  SwiftLint:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Lint
        run: npm run lint