name: Test

on:
  pull_request:
    branches:
      - main
    paths:
      - 'LastDram/**'
      - 'LastDramTests/**'
      - '.github/workflows/test.yml'

jobs:
  test:
    name: Unit Tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Run unit tests
        run: npm run test
