name: Test

on:
  pull_request:
    branches:
      - main
    paths:
      - 'LastDram/**'
      - 'LastDramTests/**'
      - '.github/workflows/test.yml'

jobs:
  test:
    name: Unit Tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run unit tests
        run: bundle exec fastlane scan --scheme "LastDramTests"
