name: Test

on:
  pull_request:
    branches:
      - main
    paths:
      - 'LastDram/**'
      - 'LastDramTests/**'
      - '.github/workflows/test.yml'

jobs:
  test:
    name: Unit Tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: actions/setup-ruby@v1

      - name: Run unit tests
        uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'test'

